INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image, url) VALUES (4.5, 2, 'The Witcher', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg', 'https://www.youtube.com/watch?v=tjujvMkqWe4&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (3.3, 3, 'Venom: Tempo de Carnificina', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg', 'https://www.youtube.com/watch?v=-BI6OOYqrxE');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Shang-Chi e a Lenda dos Dez Anéis', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cinER0ESG0eJ49kXlExM0MEWGxW.jpg', 'https://www.youtube.com/watch?v=AfHiUtxrmiY&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Matrix Resurrections', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg', 'https://www.youtube.com/watch?v=NDizFsSsX18');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Eternos', 'https://www.themoviedb.org/t/p/original/vvDk3CLqeBrYfxVJwYEn9lWOYGI.jpg', 'https://www.youtube.com/watch?v=Vv8q8UDU9_k');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Encanto', 'https://www.themoviedb.org/t/p/original/zAC6fCnaOHMpPFpOpngTSmTDnLK.jpg', 'https://www.youtube.com/watch?v=noOcCBKkxHQ&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Homem Aranha Sem Volta Para Casa', 'https://www.themoviedb.org/t/p/original/t0fSUE2KsFNGXwui9knxd3XsW8n.jpg', 'https://www.youtube.com/watch?v=EjZEzqURWJM&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Gavião Arqueiro', 'https://www.themoviedb.org/t/p/original/62qfVDg4VK3kqZFxrRztPqSbal4.jpg', 'https://www.youtube.com/watch?v=6tdxk503c7U');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Os Mercenários 2', 'https://www.themoviedb.org/t/p/original/gEDpD6l2CJ8aLbtYLL2ecQ3yk09.jpg', 'https://www.youtube.com/watch?v=AxYhnRg7qJM&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Pânico', 'https://www.themoviedb.org/t/p/original/7qrIvCcUcQGZBFLrgBLcaIcEuHd.jpg', 'https://www.youtube.com/watch?v=swzTZ2mQypM');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Duna', 'https://www.themoviedb.org/t/p/original/s9E9W77HS8zEQvsrpz5aEUTKnvD.jpg', 'https://www.youtube.com/watch?v=hfLkFZWFmLM&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'A Liga dos Monstros', 'https://www.themoviedb.org/t/p/original/pUfIDVom3KzsOLn0u4ZAg7GeEVt.jpg', 'https://www.youtube.com/watch?v=KA49KUQCU9I&feature=emb_title');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Fique Comigo', 'https://www.themoviedb.org/t/p/original/kTlqckU8MYJacGDPkX17Qi2gGx5.jpg', 'https://www.youtube.com/watch?v=9mRws6nuoPs&t=2s');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Ghostbusters: Mais Além ', 'https://www.themoviedb.org/t/p/original/e9nSrwh0H9n1YCbITxO4d2nN9xm.jpg', 'https://www.youtube.com/watch?v=Ikqtxp8Yd-U&t=1s');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Sing 2', 'https://www.themoviedb.org/t/p/original/gsyfYUFDJHq2ZB17B4mpcck29M2.jpg', 'https://www.youtube.com/watch?v=z0HBjiNDAfI');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Proxima Parada: Lar Doce Lar', 'https://www.themoviedb.org/t/p/original/9TtAmtq6iJfzh6qG4euG6eoUQDm.jpg', 'https://www.youtube.com/watch?v=5ZB-legrTPM');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Resident Evil: Bem-Vindo a Raccoon City', 'https://www.themoviedb.org/t/p/original/eStYYbyaxyDMzHVkGrmkiSrMi0h.jpg', 'https://www.youtube.com/watch?v=1cVz1wfzqbs');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'O Ultimo Duelo', 'https://www.themoviedb.org/t/p/original/mhrzzNauB1PKrwnqVbLQODNNTJN.jpg', 'https://www.youtube.com/watch?v=Z36W088SS4k');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Sem Tempo Para Morrer', 'https://www.themoviedb.org/t/p/original/iED5BlTFVky8lKw8SuG7QX0q6yI.jpg', 'https://www.youtube.com/watch?v=FlriFMTIPOg');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Finch', 'https://www.themoviedb.org/t/p/original/wn6p2NwJWKFawinkJ0OvOLQ3GLH.jpg', 'https://www.youtube.com/watch?v=CxTn0EXzZOE&t=3s');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'The Walking Dead', 'https://www.themoviedb.org/t/p/original/wZybArleWWRF8UksqEBjGsMFNMO.jpg', 'https://www.youtube.com/watch?v=qAS8f9L-vWc');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Game Of thrones', 'https://www.themoviedb.org/t/p/original/9ih9MhTx0Vwy7A1EoUdEqlaX9JD.jpg', 'https://www.youtube.com/watch?v=Ah5LiqkKBTo');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Demolidor', 'https://www.themoviedb.org/t/p/original/vNbGwybrD2vEc3asMTF36W0bVds.jpg', 'https://www.youtube.com/watch?v=y3GkQ6yoAA4');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Gotham', 'https://www.themoviedb.org/t/p/original/nOeHVzmh3uSFkcQKIlzzDtF2211.jpg', 'https://www.youtube.com/watch?v=A9fgKg0HsMs&t=2s');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Invasão do Mundo: Batalha de Los Angeles', 'https://www.themoviedb.org/t/p/original/yApEJEltSSf05tRpWtmcu0P9mun.jpg', 'https://www.youtube.com/watch?v=aPJZKOzdWOs');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Mortal Kombat', 'https://www.themoviedb.org/t/p/original/44aCR6cjH0FbzW6PMw3Ega178iW.jpg', 'https://www.youtube.com/watch?v=8Tk8sqXlogM');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Godzilla VS Kong', 'https://www.themoviedb.org/t/p/original/vqnPCE2RomLlQrdowWs7m4pdWT2.jpg', 'https://www.youtube.com/watch?v=aJMfEz2cobI');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Monster Hunter', 'https://www.themoviedb.org/t/p/original/9IdvM0W1xjwS8YBT53KrOQnZZKG.jpg', 'https://www.youtube.com/watch?v=8UUcif71zg4');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Zona de Combate', 'https://www.themoviedb.org/t/p/original/vnVQx7MJMwTvqcn5pkYDImxzlMg.jpg', 'https://www.youtube.com/watch?v=A1Dv65WAlsI');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Os Croods 2: Uma Nova Era', 'https://www.themoviedb.org/t/p/original/f7BIa9xIerwviSMsa9BEY28sC3Y.jpg', 'https://www.youtube.com/watch?v=_v0167X4n7M&t=2s');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Soul', 'https://www.themoviedb.org/t/p/original/bzDAfXoqNAvWUe7uss2NE3BmRqy.jpg', 'https://www.youtube.com/watch?v=hWBxoH4-4yw');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Raya e o Último Dragão', 'https://www.themoviedb.org/t/p/original/nFuxY9pebpnkXaZ2H06qX68eIEy.jpg', 'https://www.youtube.com/watch?v=8EWxHjHPvQM');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Mundo em Caos', 'https://www.themoviedb.org/t/p/original/oMSumadgRiygK1DUtBurdnZb9Jz.jpg', 'https://www.youtube.com/watch?v=dzrGdRVIUMo');
INSERT INTO tb_movie(score, count, title, image, url) VALUES (0, 0, 'Infinite', 'https://www.themoviedb.org/t/p/original/80gmBmKASG3hzyRB1NqcGPH2WId.jpg', 'https://www.youtube.com/watch?v=Y9aE2jO9Skg&feature=emb_title');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);
